version: '3.8'
services:

  entrypoint:
    build: ./entrypoint_service
    ports:
      - "${ENTRYPOINT_SVC_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=entrypoint
      - OTEL_EXPORTER_OTLP_ENDPOINT=datadog:${DD_GRPC_PORT}
      - TRACES_EXPORTER=otel
      - METRICS_EXPORTER=otel
      - LOGS_EXPORTER=otel
      - ENDPOINT_SERVICE_A=service_a:5000
      - ENDPOINT_SERVICE_B=service_b:5000
      - SELF_PORT=5000

  service_a:
    build: ./service_a
    ports:
      - "${SVC_A_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=service_a
      - OTEL_EXPORTER_OTLP_ENDPOINT=datadog:${DD_GRPC_PORT}
      - TRACES_EXPORTER=otel
      - METRICS_EXPORTER=noop
      - LOGS_EXPORTER=noop
      - ENDPOINT_SERVICE_B=service_b:5000
      - SELF_PORT=5000

  service_b:
    build: ./service_b
    ports:
      - "${SVC_B_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=service_b
      - OTEL_EXPORTER_OTLP_ENDPOINT=datadog:${DD_GRPC_PORT}
      - TRACES_EXPORTER=otel
      - METRICS_EXPORTER=noop
      - LOGS_EXPORTER=noop
      - SELF_PORT=5000

  datadog:
    image: datadog/agent:latest
    ports:
      - "${DD_GRPC_PORT}:4317"
    networks:
      - microservices_network
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE}
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:${DD_GRPC_PORT}
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
      - DD_HOSTNAME=datadog

networks:
  microservices_network:
    driver: bridge
