version: '3.8'
services:

  entrypoint:
    build: ./entrypoint_service
    ports:
      - "${ENTRYPOINT_SVC_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=entrypoint
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:${COLLECTOR_GRPC_PORT}
      - TRACES_EXPORTER=noop
      - METRICS_EXPORTER=stdout
      - LOGS_EXPORTER=noop

  service_a:
    build: ./service_a
    ports:
      - "${SVC_A_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=service_a
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:${COLLECTOR_GRPC_PORT}
      - TRACES_EXPORTER=noop
      - METRICS_EXPORTER=stdout
      - LOGS_EXPORTER=noop

  service_b:
    build: ./service_b
    ports:
      - "${SVC_B_PORT}:5000"
    networks:
      - microservices_network
    environment:
      - SERVICE_NAME=service_b
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:${COLLECTOR_GRPC_PORT}
      - TRACES_EXPORTER=noop
      - METRICS_EXPORTER=stdout
      - LOGS_EXPORTER=noop

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "${COLLECTOR_GRPC_PORT}:4317"
      - "${COLLECTOR_HTTP_PORT}:4318"
    networks:
      - microservices_network
    volumes:
      - ./collector/collector-config.yml:/etc/collector-config.yml
    command: ["--config", "/etc/collector-config.yml"]

networks:
  microservices_network:
    driver: bridge
